services:

    # I admit the bummer and wonder myself: Why not sugarcrm_wrapper?
    BisonLab\SugarCrmBundle\Service\SugarWrapper:
        arguments:
            - "%env(SUGARCRM_BASE_URL)%"
            - "%env(SUGARCRM_USERNAME)%"
            - "%env(SUGARCRM_PASSWORD)%"
            - "sugar-wrapper"

    sugar_wrapper:
        alias: BisonLab\SugarCrmBundle\Service\SugarWrapper
        public: true
