services:
    # I admit the bummer and wonder myself: Why not sugarcrem_wrapper?
    sugar_wrapper:
        class: BisonLab\SugarCrmBundle\Service\SugarWrapper
        public: true
        arguments:
            - "%env(SUGARCRM_BASE_URL)%"
            - "%env(SUGARCRM_USERNAME)%"
            - "%env(SUGARCRM_PASSWORD)%"
            - "sugar-wrapper"

    BisonLab\SugarCrmBundle\Command\:
        resource: '../Command/*'
        tags: ['console.command']
        arguments: [ '@sugar_wrapper', null, null, null, null, null ]
