services:
    BisonLab\NoOrmBundle\Services\SugarCrmRestReadonly:
        arguments:
            - "%env(SUGARCRM_BASE_URL)%"
            - "%env(SUGARCRM_USERNAME)%"
            - "%env(SUGARCRM_PASSWORD)%"
            - "sugar-wrapper"

    sugarcrm_rest:
        alias: BisonLab\NoOrmBundle\Services\SugarCrmRestReadonly
        public: true

    BisonLab\SugarCrmBundle\Manager\Account:
        autowire: true
        autoconfigure: true

    sugarcrm_account_manager:
        alias: BisonLab\SugarCrmBundle\Manager\Account
        public: true

    BisonLab\SugarCrmBundle\Manager\Product:
        autowire: true
        autoconfigure: true

    sugarcrm_product_manager:
        alias: BisonLab\SugarCrmBundle\Manager\Product
        public: true

    BisonLab\SugarCrmBundle\Manager\ProductTemplate:
        autowire: true
        autoconfigure: true

    sugarcrm_product_template_manager:
        alias: BisonLab\SugarCrmBundle\Manager\ProductTemplate
        public: true

    BisonLab\SugarCrmBundle\Manager\ProductCategory:
        autowire: true
        autoconfigure: true

    sugarcrm_product_category_manager:
        alias: BisonLab\SugarCrmBundle\Manager\ProductCategory
        public: true

    BisonLab\SugarCrmBundle\Command\:
        resource: '../Command/*'
        autowire: true
        autoconfigure: true
        tags: ['console.command']
