services:
    sugarcrm_rest:
        class: BisonLab\NoOrmBundle\Services\SugarCrmRestReadonly
        public: true
        arguments:
            - "%env(SUGARCRM_BASE_URL)%"
            - "%env(SUGARCRM_USERNAME)%"
            - "%env(SUGARCRM_PASSWORD)%"
            - "sugar-wrapper"

    sugarcrm_account_manager:
        class: BisonLab\SugarCrmBundle\Manager\Account
        public: true
        arguments: [ "@sugarcrm_rest" ]

    sugarcrm_product_manager:
        class: BisonLab\SugarCrmBundle\Manager\Product
        public: true
        arguments: [ "@sugarcrm_rest" ]

    sugarcrm_product_template_manager:
        class: BisonLab\SugarCrmBundle\Manager\ProductTemplate
        public: true
        arguments: [ "@sugarcrm_rest" ]

    sugarcrm_product_category_manager:
        class: BisonLab\SugarCrmBundle\Manager\ProductCategory
        public: true
        arguments: [ "@sugarcrm_rest" ]

    BisonLab\SugarCrmBundle\Command\:
        resource: '../Command/*'
        tags: ['console.command']
        arguments: [ null, '@sugarcrm_account_manager', '@sugarcrm_product_manager', '@sugarcrm_product_category_manager', '@sugarcrm_product_template_manager' ]
